package de.emir.model.universal.detection;

import de.emir.model.universal.physics.PhysicalObject;
import de.emir.model.universal.units.Angle;
import de.emir.model.universal.units.Distance;
import de.emir.model.universal.units.Time;
import de.emir.tuml.ucore.runtime.annotations.UMLClass;
import de.emir.tuml.ucore.runtime.annotations.UMLProperty;
import de.emir.tuml.ucore.runtime.annotations.UMLProperty.AssociationType;

/**

    * A Target is a single detection point generated by the detection system. It consists
    * of a detection timestamp, unique ID and bearing/distance to a reference point. This
    * is usually the location of the sensor which detected the object. While the Target can also
    * contain a georeferenced location as part of the Pose, this is usually calculated using
    * the distance/bearing references. The name, properties and position is inherited from
    * PhysicalObject. Compared to a TrackedTarget, the Target is a single observation point
    * and has not been linked to an identity by a tracking system.
 * @generated 
 */
@UMLClass(name = "Target", parent = PhysicalObject.class)	
public interface ITarget extends PhysicalObject 
{
	/**
	 Unique identifier of the detected Target. 
	 * @generated 
	 */
	@UMLProperty(name = "id", associationType = AssociationType.PROPERTY)
	public void setId(String _id);
	/**
	 Unique identifier of the detected Target. 
	 * @generated 
	 */
	@UMLProperty(name = "id", associationType = AssociationType.PROPERTY)
	public String getId();
	/**
	 Timestamp of the detection of the Target. 
	 * @generated 
	 */
	@UMLProperty(name = "timestamp", associationType = AssociationType.PROPERTY)
	public void setTimestamp(Time _timestamp);
	/**
	 Timestamp of the detection of the Target. 
	 * @generated 
	 */
	@UMLProperty(name = "timestamp", associationType = AssociationType.PROPERTY)
	public Time getTimestamp();
	/**
	 Reference object from which the detection was made. This could be a sensor or vessel. 
	 * @generated 
	 */
	@UMLProperty(name = "reference", associationType = AssociationType.PROPERTY)
	public void setReference(PhysicalObject _reference);
	/**
	 Reference object from which the detection was made. This could be a sensor or vessel. 
	 * @generated 
	 */
	@UMLProperty(name = "reference", associationType = AssociationType.PROPERTY)
	public PhysicalObject getReference();
	/**
	 Distance to the reference object from which the detection was made. 
	 * @generated 
	 */
	@UMLProperty(name = "referenceDistance", associationType = AssociationType.PROPERTY)
	public void setReferenceDistance(Distance _referenceDistance);
	/**
	 Distance to the reference object from which the detection was made. 
	 * @generated 
	 */
	@UMLProperty(name = "referenceDistance", associationType = AssociationType.PROPERTY)
	public Distance getReferenceDistance();
	/**
	 Bearing to the reference object from which the detection was made. 
	 * @generated 
	 */
	@UMLProperty(name = "referenceBearing", associationType = AssociationType.PROPERTY)
	public void setReferenceBearing(Angle _referenceBearing);
	/**
	 Bearing to the reference object from which the detection was made. 
	 * @generated 
	 */
	@UMLProperty(name = "referenceBearing", associationType = AssociationType.PROPERTY)
	public Angle getReferenceBearing();

	
}
