package de.emir.model.application.sense.measurements;

import de.emir.model.application.sense.Measurement;
import de.emir.model.universal.physics.LocatableObject;
import de.emir.tuml.ucore.runtime.annotations.UMLClass;
import de.emir.tuml.ucore.runtime.annotations.UMLProperty;
import de.emir.tuml.ucore.runtime.annotations.UMLProperty.AssociationType;

/**
 The position Measurement differs from the LocationMeasurement in that form, that it measures the position
 * of an external object. Within the maritime domain such a measurement may be generated by an AIS sensor but also 
 * by an Radar (reasoned from the own position of the radar and a DistanceMeasurement) 
 * @generated 
 */
@UMLClass(parent = Measurement.class)	
public interface PositionMeasurement extends Measurement 
{
	/**
	 *	@generated 
	 */
	@UMLProperty(name = "object", associationType = AssociationType.PROPERTY)
	public void setObject(LocatableObject _object);
	/**
	 *	@generated 
	 */
	@UMLProperty(name = "object", associationType = AssociationType.PROPERTY)
	public LocatableObject getObject();

	
}
