package de.emir.model.application.sense.ports;

import de.emir.model.application.sense.SensorPort;
import de.emir.model.application.sense.measurements.PositionMeasurement;
import de.emir.tuml.ucore.runtime.annotations.UMLClass;
import de.emir.tuml.ucore.runtime.annotations.UMLProperty;
import de.emir.tuml.ucore.runtime.annotations.UMLProperty.AssociationType;

/**
 The position Measurement differs from the LocationMeasurement in that form, that it measures the position
 * of an external object. Within the maritime domain such a measurement may be generated by an AIS sensor but also 
 * by an Radar (reasoned from the own position of the radar and a DistanceMeasurement) 
 * @generated 
 */
@UMLClass(parent = SensorPort.class)	
public interface PositionPort extends SensorPort 
{
	/**
	 *	@generated 
	 */
	@UMLProperty(name = "measurement", associationType = AssociationType.PROPERTY)
	public void setMeasurement(PositionMeasurement _measurement);
	/**
	 *	@generated 
	 */
	@UMLProperty(name = "measurement", associationType = AssociationType.PROPERTY)
	public PositionMeasurement getMeasurement();

	
}
