package de.emir.model.universal.detection.impl;

import de.emir.tuml.ucore.runtime.annotations.UMLImplementation;
import de.emir.tuml.ucore.runtime.UClass;
import de.emir.model.universal.detection.ITarget;
import de.emir.model.universal.detection.TargetPackage;
import de.emir.model.universal.core.MemberObserver;
import de.emir.model.universal.core.RSIdentifier;
import de.emir.model.universal.physics.ICapability;
import de.emir.model.universal.physics.ICharacteristic;
import de.emir.model.universal.physics.PhysicalObject;
import de.emir.model.universal.physics.RelativeEngineering2D;
import de.emir.model.universal.physics.impl.PhysicalObjectImpl;
import de.emir.model.universal.spatial.Pose;
import de.emir.model.universal.units.Angle;
import de.emir.model.universal.units.Distance;
import de.emir.model.universal.units.Time;
import de.emir.tuml.ucore.runtime.Notification;
import de.emir.tuml.ucore.runtime.NotificationType;
import java.util.List;


/**

    * A Target is a single detection point generated by the detection system. It consists
    * of a detection timestamp, unique ID and bearing/distance to a reference point. This
    * is usually the location of the sensor which detected the object. While the Target can also
    * contain a georeferenced location as part of the Pose, this is usually calculated using
    * the distance/bearing references. The name, properties and position is inherited from
    * PhysicalObject.
 * @generated 
 */
@UMLImplementation(classifier = ITarget.class)
public class TargetImpl extends PhysicalObjectImpl implements ITarget  
{
	
	
	/**
	 Unique identifier of the detected Target. 
	 * @generated 
	 */
	private String mId = "";
	/**
	 Timestamp of the detection of the Target. 
	 * @generated 
	 */
	private Time mTimestamp = null;
	/**
	 Reference object from which the detection was made. This could be a sensor or vessel. 
	 * @generated 
	 */
	private PhysicalObject mReference = null;
	/**
	 Distance to the reference object from which the detection was made. 
	 * @generated 
	 */
	private Distance mReferenceDistance = null;
	/**
	 Bearing to the reference object from which the detection was made. 
	 * @generated 
	 */
	private Angle mReferenceBearing = null;
			
	/**
	 *	Default constructor
	 *	@generated
	 */
	public TargetImpl(){
		super();
		//set the default values and assign them to this instance 
		setTimestamp(mTimestamp);
		setReference(mReference);
		setReferenceDistance(mReferenceDistance);
		setReferenceBearing(mReferenceBearing);
	}
	
	/**
	 *	Default copy constructor
	 *	@generated
	 */
	public TargetImpl(final ITarget _copy) {
		super(_copy);
		mId = _copy.getId();
		mTimestamp = _copy.getTimestamp();
		mReference = _copy.getReference();
		mReferenceDistance = _copy.getReferenceDistance();
		mReferenceBearing = _copy.getReferenceBearing();
	}
	
	/**
	 *	Default attribute constructor
	 *	@generated
	 */
	public TargetImpl(RSIdentifier _name, List<String> _allias, String _remarks, List<MemberObserver> _observers, RSIdentifier _identifier, RelativeEngineering2D _ownedCoordinateSystem, Pose _pose, List<ICharacteristic> _characteristics, List<ICapability> _capabilities, List<PhysicalObject> _children, String _id, Time _timestamp, PhysicalObject _reference, Distance _referenceDistance, Angle _referenceBearing) {
		super(_name,_allias,_remarks,_observers,_identifier,_ownedCoordinateSystem,_pose,_characteristics,_capabilities,_children);
		mId = _id;
		mTimestamp = _timestamp; 
		mReference = _reference; 
		mReferenceDistance = _referenceDistance; 
		mReferenceBearing = _referenceBearing; 
	}
	
	/**
	 * @generated
	 */
	public UClass getUClassifier() {
		return TargetPackage.Literals.Target;
	}
	
	//////////////////////////////////////////////////////////////////
	//						Setter / Getter							//
	//////////////////////////////////////////////////////////////////
	/**
	 Unique identifier of the detected Target. 
	 * @generated 
	 */
	public void setId(String _id) {
		if (needNotification(TargetPackage.Literals.Target_id)){
			String _oldValue = mId;
			mId = _id;
			notify(_oldValue, _id, TargetPackage.Literals.Target_id, NotificationType.SET);
		}else{
			mId = _id;
		}
	}
	/**
	 Unique identifier of the detected Target. 
	 * @generated 
	 */
	public String getId() {
		return mId;
	}
	/**
	 Timestamp of the detection of the Target. 
	 * @generated 
	 */
	public void setTimestamp(Time _timestamp) {
		Notification<Time> notification = basicSet(mTimestamp, _timestamp, TargetPackage.Literals.Target_timestamp);
		mTimestamp = _timestamp;
		if (notification != null){
			dispatchNotification(notification);
		}
	}
	/**
	 Timestamp of the detection of the Target. 
	 * @generated 
	 */
	public Time getTimestamp() {
		return mTimestamp;
	}
	/**
	 Reference object from which the detection was made. This could be a sensor or vessel. 
	 * @generated 
	 */
	public void setReference(PhysicalObject _reference) {
		Notification<PhysicalObject> notification = basicSet(mReference, _reference, TargetPackage.Literals.Target_reference);
		mReference = _reference;
		if (notification != null){
			dispatchNotification(notification);
		}
	}
	/**
	 Reference object from which the detection was made. This could be a sensor or vessel. 
	 * @generated 
	 */
	public PhysicalObject getReference() {
		return mReference;
	}
	/**
	 Distance to the reference object from which the detection was made. 
	 * @generated 
	 */
	public void setReferenceDistance(Distance _referenceDistance) {
		Notification<Distance> notification = basicSet(mReferenceDistance, _referenceDistance, TargetPackage.Literals.Target_referenceDistance);
		mReferenceDistance = _referenceDistance;
		if (notification != null){
			dispatchNotification(notification);
		}
	}
	/**
	 Distance to the reference object from which the detection was made. 
	 * @generated 
	 */
	public Distance getReferenceDistance() {
		return mReferenceDistance;
	}
	/**
	 Bearing to the reference object from which the detection was made. 
	 * @generated 
	 */
	public void setReferenceBearing(Angle _referenceBearing) {
		Notification<Angle> notification = basicSet(mReferenceBearing, _referenceBearing, TargetPackage.Literals.Target_referenceBearing);
		mReferenceBearing = _referenceBearing;
		if (notification != null){
			dispatchNotification(notification);
		}
	}
	/**
	 Bearing to the reference object from which the detection was made. 
	 * @generated 
	 */
	public Angle getReferenceBearing() {
		return mReferenceBearing;
	}
	

	/**
	* @generated
	*/
	@Override
	public String toString() {
		return "TargetImpl{" +
		" allias = " + getAllias() + 
		" remarks = " + getRemarks() + 
		" id = " + getId() + 
		"}";
	}
}
